import Link from 'next/link';
import { notFound } from 'next/navigation';
import { load } from '@/lib/api';
import { count, date, dayLabel, label, sentTime, proxyNote, duration as formatDuration } from '@/lib/format.mjs';
import type { DayDetail, Row } from '@/lib/types';
import { PageHeader, DataError, Stat, Empty, DetailList, Disclosure, Badge, Timeline } from '@/components/ui';

export const metadata = { title: 'Tagesbilanz' };
export default async function DayPage({ params }: { params: Promise<{ day: string }> }) {
  const { day } = await params;
  if (!/^\d{4}-\d{2}-\d{2}$/.test(day) || !Number.isFinite(Date.parse(day)) || new Date(day).toISOString().slice(0,10) !== day) notFound();
  const result = await load<DayDetail>(`/v1/dashboard/days/${day}`);
  if (result.error) return <><PageHeader title={dayLabel(day)}/><DataError message={result.error}/></>;
  const { counts, sent, pipeline, variableCosts, reporting = {}, funnel = {}, quizSubmissions = [] } = result.data!;
  const measured = Boolean(pipeline?.runs?.length);
  const duration = (value: unknown) => formatDuration(value, measured);
  const costs = variableCosts?.knownByCurrency || {};
  return <><Link href="/days" className="back-link">← Tage</Link><PageHeader title={dayLabel(day)}><span className="small muted">Berlin</span></PageHeader>
    {reporting?.reassignedTo?.length > 0 && <p className="data-note">Diese Recherche wird in der gemeinsamen Tageszeile geführt: {reporting.reassignedTo.map((target: string) => <Link key={target} href={`/days/${target}`}>{dayLabel(target)}</Link>)}.</p>}
    <dl className="stats"><Stat title="Kandidaten" value={counts.consideredCandidates ?? counts.searchedCandidates ?? 0} hint="Unterschiedliche Kandidaten der zugeordneten Recherche. Jede Firma zählt einmal; erneute Regelprüfungen erhöhen die Zahl nicht."/><Stat title="Qualifiziert" value={counts.qualifiedCandidates ?? 0} hint="Unterschiedliche passende Firmen aus dieser Recherche. Noch nicht versendete E-Mails zählen weiterhin nur als qualifiziert."/><Stat title="E-Mails versendet" value={counts.sentMessages ?? 0} hint={proxyNote(counts)}/><Stat title="Zugestellt" value={counts.deliveredMessages ?? 0} hint="Vom Anbieter gemeldete Zustellungen. Kein Nachweis, dass die E-Mail gelesen wurde oder im Posteingang statt im Spamordner liegt."/></dl>
    {counts.reportedPipelineDayAssigned && <p className="data-note">Die Recherche vom {(counts.pipelineOriginalDays || []).map(dayLabel).join(', ')} ist diesem Pilot-Tag zugeordnet.</p>}
    {reporting?.assignments?.length > 0 && <Disclosure title="Tageszuordnung"><p>Recherche und Versand sind hier für den gemeinsamen Pilot zusammengefasst. Die ursprünglichen Recherchezeitpunkte bleiben in den Bearbeitungsdetails erhalten. Dauer und Kosten betreffen den zugeordneten Rechercheaufwand.</p>{reporting.supplementalRuns?.length > 0 && <><p className="data-note">Zusätzliche Regelprüfungen vorhandener Belege erhöhen die Kandidaten- oder Qualifiziertenzahl nicht:</p><ul className="plain-list">{reporting.supplementalRuns.map((run: Row) => <li key={run.id}>{label(run.kind)} · {date(run.startedAt)}<p>{count(run.checkedCandidates)} Prüfungen, {count(run.qualifiedCandidates)} positive Ergebnisse</p></li>)}</ul></>}</Disclosure>}
    {funnel?.candidates?.length > 0 && <Disclosure title="Kandidaten" meta={`${count(funnel.candidates.length)} Firmen`}><div className="table-scroll"><table><thead><tr><th>Firma</th><th>Ergebnis</th></tr></thead><tbody>{funnel.candidates.map((candidate: Row) => <tr key={candidate.id}><td>{candidate.companyId ? <Link className="row-link" href={`/leads/${candidate.companyId}`}>{candidate.companyName || candidate.candidateKeys?.[0]}</Link> : candidate.companyName || candidate.candidateKeys?.[0]}</td><td><Badge value={candidate.outcome}/></td></tr>)}</tbody></table></div></Disclosure>}
    {quizSubmissions.length > 0 && <Disclosure title="Quiz-Abschlüsse"><Timeline items={quizSubmissions}/></Disclosure>}
    <section className="section"><div className="section-heading"><h2>E-Mails</h2><span className="small muted">{count(sent.length)} {sent.length === 1 ? 'Sendung' : 'Sendungen'}</span></div>{counts.sentTimeProxyMessages > 0 && <p className="notice warning">{proxyNote(counts)}</p>}{!sent.length ? <Empty title="Keine Sendung an diesem Tag erfasst"/> : <div className="table-scroll"><table><thead><tr><th>Unternehmen</th><th>Betreff</th><th>Zeitpunkt</th><th><span className="sr-only">Mail</span></th></tr></thead><tbody>{sent.map(mail => <tr key={mail.messageId}><td><Link className="row-link" href={`/leads/${mail.companyId}`}>{mail.companyName}</Link></td><td><Link href={`/messages/${mail.messageId}`}>{mail.subject || '(Ohne Betreff)'}</Link></td><td>{sentTime(mail)}</td><td className="row-end"><Link aria-label={`Mail ${mail.subject || 'ohne Betreff'} öffnen`} href={`/messages/${mail.messageId}`}>→</Link></td></tr>)}</tbody></table></div>}</section>
    <Disclosure title={counts.reportedPipelineDayAssigned ? 'Zugeordneter Rechercheaufwand' : 'Bearbeitung'} meta={measured ? duration(pipeline.elapsedWallClockMs) : 'Nicht erfasst'}>{!measured ? <p>Keine Bearbeitungszeiten erfasst.</p> : <><DetailList items={[
      ['Suchversuche', count(pipeline.coverage?.search ? pipeline.searchAttempts : null)], ['Ausgeschlossen', count(pipeline.coverage?.qualification ? pipeline.decisions?.excluded : null)], ['Nicht passend', count(pipeline.coverage?.qualification ? pipeline.decisions?.not_qualified : null)], ['Prüfung offen', count(pipeline.coverage?.qualification ? pipeline.decisions?.needs_review : null)], ['Angereichert', count(pipeline.coverage?.enrichment ? pipeline.enrichmentCandidates : null)], ['Texte erstellt', count(pipeline.coverage?.authoring ? pipeline.authoredCandidates : null)], ['Wiederholungen', count(pipeline.retryAttempts)], ['Fehlgeschlagene Schritte', count(pipeline.failures)], ['Laufzeit', duration(pipeline.elapsedWallClockMs)], ['Schrittzeiten', duration(pipeline.summedStepDurationMs)],
    ]}/>{pipeline?.runs?.some((run: Row) => run.context?.usesExistingEvidence) && <p className="data-note">Erneute Regelbewertung vorhandener Belege. Die Dauer ist kein ursprünglicher Rechercheaufwand.</p>}<ul className="plain-list">{pipeline.runs.map((run: Row) => <li key={run.id}>{label(run.kind)}<p>{date(run.startedAt,true)} – {run.finishedAt ? date(run.finishedAt,true) : 'offen'}</p></li>)}</ul></>}</Disclosure>
    <Disclosure title="Versandereignisse"><DetailList items={[
      ['Anbieter angenommen', count(counts.acceptedMessages)], ['Zugestellt', count(counts.deliveredMessages)], ['Rückläufer', count(counts.bounces)], ['Verzögerungen', count(counts.deferrals)], ['Beschwerden', count(counts.complaints)], ['Abmeldungen', count(counts.optOuts)],
    ]}/></Disclosure>
    <Disclosure title="Variable Kosten" meta={Object.keys(costs).length ? 'Erfasste Teilsummen' : 'Nicht erfasst'}>{Object.keys(costs).length ? <DetailList items={Object.entries(costs).map(([currency,value]) => [currency, `${new Intl.NumberFormat('de-DE',{minimumFractionDigits:2,maximumFractionDigits:6}).format(typeof value === 'number' ? value : (value as Row).knownSubtotal)} ${currency}`])}/> : <p>Noch keine Beträge erfasst.</p>}{variableCosts?.unknownSteps > 0 && <p className="data-note">{count(variableCosts.unknownSteps)} Schritte ohne Kostenerfassung.</p>}<p className="data-note">Bekannte variable Kosten, ohne Abos oder Umlage.</p></Disclosure>
  </>;
}
